name: Release

on:
  push:
    branches:
      - $default-branch

jobs:
  release:
    name: Release
    uses: primer/.github/.github/workflows/release.yml@v3.0.0
    with:
      app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
    secrets:
      app-private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
