name: Release

on:
  push:
    branches:
      - 'changeset-release/main'

jobs:
  release-candidate:
    name: Candidate
    uses: primer/.github/.github/workflows/release_candidate.yml@bb0b18fb589038a93a49a24624be0559c01ed0b9 # v1.0.0
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
