name: Release

on:
  push:
    branches-ignore:
      - $default-branch
      - "changeset-release/main"

jobs:
  release-canary:
    name: Canary
    uses: primer/.github/.github/workflows/release_canary.yml@v3.0.0
    with:
      app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
    secrets:
      app-private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
