# Use the primer GitHub App for authentication.
# See: https://github.com/organizations/primer/settings/apps/primer

name: Get an access token from the primer App

on:
  workflow_call:

jobs:
  get-access-token:
    name: Get access token
    runs-on: ubuntu-latest
    steps:
      - uses: camertron/github-app-installation-auth-action@v1
        with:
          app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
          private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
          client-id: ${{ vars.PRIMER_APP_CLIENT_ID_SHARED }}
          client-secret: ${{ secrets.PRIMER_APP_CLIENT_SECRET_SHARED }}
          installation-id: ${{ vars.PRIMER_APP_INSTALLATION_ID_SHARED }}
