# Use the primer GitHub App for authentication.
# See: https://github.com/organizations/primer/settings/apps/primer

name: Get an access token from the primer App

on:
  workflow_call:
    outputs:
      access-token:
        description: "An access token for the given installation."
        value: ${{ jobs.run.steps.get-access-token.outputs.access-token }}

jobs:
  run:
    name: Get access token
    runs-on: ubuntu-latest
    outputs:
      access-token: ${{ steps.get-access-token.outputs.access-token }}
    steps:
      - id: get-access-token
        uses: camertron/github-app-installation-auth-action@v1
        with:
          app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
          private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
          client-id: ${{ vars.PRIMER_APP_CLIENT_ID_SHARED }}
          client-secret: ${{ secrets.PRIMER_APP_CLIENT_SECRET_SHARED }}
          installation-id: ${{ vars.PRIMER_APP_INSTALLATION_ID_SHARED }}
