name: 'PagerDuty Schedule'
description: 'Get information about the given PagerDuty Schedule'

on:
  workflow_dispatch:
    inputs:
      schedule-id:
        description: 'The id of the schedule'
        required: true
      token:
        description: 'The API token used for making requests to PagerDuty'
        required: true

jobs:
  default:
    runs-on: ubuntu-latest
    outputs:
      user: ${{ steps.pagerduty.outputs.user }}
      start: ${{ steps.pagerduty.outputs.start }}
      end: ${{ steps.pagerduty.outputs.end }}
      id: ${{ steps.pagerduty.outputs.id }}
      previous-schedule-start: ${{ steps.pagerduty.outputs.previous-schedule-start }}
      previous-schedule-end: ${{ steps.pagerduty.outputs.previous-schedule-end }}
      previous-schedule-id: ${{ steps.pagerduty.outputs.previous-schedule-id }}
      previous-schedule-user: ${{ steps.pagerduty.outputs.previous-schedule-user }}
    steps:
      - name: Get PagerDuty Schedule
        id: pagerduty
        uses: ./.github/actions/pagerduty
        with:
          schedule-id: ${{ github.event.inputs.schedule-id }}
          token: ${{ github.event.inputs.token }}
