name: 'PagerDuty Schedule'
description: 'Get information about the given PagerDuty Schedule'

on:
  workflow_call:
    outputs:
      user:
        description: 'The user who is on call for the final schedule'
        value: ${{ jobs.default.outputs.user }}
      start:
        description: 'The start date for the final schedule'
        value: ${{ jobs.default.outputs.start }}
      end:
        description: 'The end date for the final schedule'
        value: ${{ jobs.default.outputs.end }}
      id:
        description: 'The id for the final schedule'
        value: ${{ jobs.default.outputs.id }}
      previous-schedule-start:
        description: 'The start date for the previous final schedule'
        value: ${{ jobs.default.outputs.previous-schedule-start }}
      previous-schedule-end:
        description: 'The end date for the previous final schedule'
        value: ${{ jobs.default.outputs.previous-schedule-end }}
      previous-schedule-id:
        description: 'The id for the previous final schedule'
        value: ${{ jobs.default.outputs.previous-schedule-id }}
      previous-schedule-user:
        description: 'The individual on call for the previous final schedule'
        value: ${{ jobs.default.outputs.previous-schedule-user }}
    inputs:
      schedule-id:
        type: string
        description: 'The id of the schedule'
        required: true
    secrets:
      token:
        description: 'The API token used for making requests to PagerDuty'
        required: true

jobs:
  default:
    runs-on: ubuntu-latest
    outputs:
      user: ${{ steps.pagerduty.outputs.user }}
      start: ${{ steps.pagerduty.outputs.start }}
      end: ${{ steps.pagerduty.outputs.end }}
      id: ${{ steps.pagerduty.outputs.id }}
      previous-schedule-start: ${{ steps.pagerduty.outputs.previous-schedule-start }}
      previous-schedule-end: ${{ steps.pagerduty.outputs.previous-schedule-end }}
      previous-schedule-id: ${{ steps.pagerduty.outputs.previous-schedule-id }}
      previous-schedule-user: ${{ steps.pagerduty.outputs.previous-schedule-user }}
    steps:
      - name: Get PagerDuty Schedule
        id: pagerduty
        uses: primer/.github/.github/actions/pagerduty
        with:
          schedule-id: ${{ inputs.schedule-id }}
          token: ${{ secrets.token }}
