on:
  workflow_call:
    inputs:
      label:
        type: string
        required: false
    secrets:
      GH_GH_PAT:
        required: true

permissions:
  contents: write
  pull-requests: write

name: Create pull request for primer/react release candidate

jobs:
  guard:
    runs-on: ubuntu-latest
    outputs:
      release-candidate-pr: ${{ steps.release-candidate-pr.outputs.number }}
    steps:
      - name: Find release candidate PR
        uses: juliangruber/find-pull-request-action@v1
        id: release-candidate-pr
        with:
          repo: primer/react
          branch: primer:changeset-release/main
      - run: echo "Release candidate - ${{ steps.release-candidate-pr.outputs.number }}"
      - name: Fail if there is no release candidate
        if: ${{ steps.release-candidate-pr.outputs.number == null }}
        run: exit 1

  nightly:
    needs: guard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_GH_PAT: ${{ secrets.GH_GH_PAT }}

      - name: Install primer/react release candidate
        run: npm install @primer/react@next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_GH_PAT: ${{ secrets.GH_GH_PAT }}

      - name: Get primer/react version
        id: primer-react-version
        uses: actions/github-script@v5
        with:
          script: |
            const pkg = require('./package.json')
            return pkg.devDependencies['@primer/react']          
      
      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v4
        with: 
          token: ${{ secrets.GH_GH_PAT }}
          base: main
          branch: primer/react-nightly
          draft: true
          delete-branch: true
          labels: ${{ inputs.label }}
          title: 'Integration tests for primer/react ${{ steps.primer-react-version.outputs.result }}'
          body: |
            - Release candidate: https://github.com/primer/react/pull/${{ needs.guard.outputs.release-candidate-pr }}
            - Auto-generated by [primer-react-nightly github action](https://github.com/primer/.github/blob/main/.github/workflows/primer_react_nightly.yml)
    
      - name: Check outputs
        if: ${{ steps.pr.outputs.pull-request-number }}
        run: echo "Pull Request URL - ${{ steps.pr.outputs.pull-request-url }}"
