name: Assign Release Conductor

on:
  push:
  workflow_dispatch:

jobs:
  assign-release-conductor:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # PVC
          # - schedule_id: 'PCCKSZ5'
          #   name: View Component Release Conductor
          #   team_slug: view-components-release-conductor
          # PRC
          - schedule_id: 'P3IIVC4'
            name: React Release Conductor
            team_slug: react-release-conductor
    steps:
      - uses: actions/checkout@v4
      # - uses: ./.github/pagerduty
      #   id: pagerduty
      #   with:
      #     schedule-id: ${{ matrix.schedule_id }}
      #     token: ${{ secrets.PAGERDUTY_TOKEN_SHARED }}
      # - run: echo ${{ steps.pagerduty.outputs.user }} is the ${{ matrix.name }}
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.PRIMER_APP_ID_SHARED }}
          private-key: ${{ secrets.PRIMER_APP_PRIVATE_KEY_SHARED }}
      - uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const currentMember = await github.request('GET /orgs/{org}/teams/{team_slug}/members', {
              org: 'primer',
              team_slug: '${{ matrix.team_slug }}',
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            })
            console.log(currentMember['data'])
